// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("EpiEvents.Core")]
[assembly: AssemblyVersionAttribute("1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright Maris Krivtezs 2018")]
[assembly: AssemblyCompanyAttribute("Maris Krivtezs")]
[assembly: AssemblyDescriptionAttribute("An in-process messaging style event handling for Episerver")]
[assembly: AssemblyTitleAttribute("EpiEvents.Core")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "EpiEvents.Core";
        internal const System.String AssemblyVersion = "1.2.0";
        internal const System.String AssemblyFileVersion = "1.2.0";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyCopyright = "Copyright Maris Krivtezs 2018";
        internal const System.String AssemblyCompany = "Maris Krivtezs";
        internal const System.String AssemblyDescription = "An in-process messaging style event handling for Episerver";
        internal const System.String AssemblyTitle = "EpiEvents.Core";
    }
}
